version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: info
      POSTGRES_PASSWORD: info
      POSTGRES_DB: infochallenger
    ports:
      - "5432:5432"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
    postgres: